// ReSharper disable once CppMissingIncludeGuard
#pragma push_macro("RETURN_IF_FAILED")
#pragma push_macro("RETURN_IF_WIN32_BOOL_FALSE")
#pragma push_macro("RETURN_IF_WIN32_ERROR")
#pragma push_macro("RETURN_IF_NULL_ALLOC")
#pragma push_macro("RETURN_HR_IF")
#pragma push_macro("RETURN_HR_IF_NULL")
#pragma push_macro("RETURN_LAST_ERROR_IF")
#pragma push_macro("RETURN_LAST_ERROR_IF_NULL")
#pragma push_macro("RETURN_IF_NTSTATUS_FAILED")
#undef RETURN_IF_FAILED
#undef RETURN_IF_WIN32_BOOL_FALSE
#undef RETURN_IF_WIN32_ERROR
#undef RETURN_IF_NULL_ALLOC
#undef RETURN_HR_IF
#undef RETURN_HR_IF_NULL
#undef RETURN_LAST_ERROR_IF
#undef RETURN_LAST_ERROR_IF_NULL
#undef RETURN_IF_NTSTATUS_FAILED
#define RETURN_IF_FAILED RETURN_IF_FAILED_EXPECTED
#define RETURN_IF_WIN32_BOOL_FALSE RETURN_IF_WIN32_BOOL_FALSE_EXPECTED
#define RETURN_IF_WIN32_ERROR RETURN_IF_WIN32_ERROR_EXPECTED
#define RETURN_IF_NULL_ALLOC RETURN_IF_NULL_ALLOC_EXPECTED
#define RETURN_HR_IF RETURN_HR_IF_EXPECTED
#define RETURN_HR_IF_NULL RETURN_HR_IF_NULL_EXPECTED
#define RETURN_LAST_ERROR_IF RETURN_LAST_ERROR_IF_EXPECTED
#define RETURN_LAST_ERROR_IF_NULL RETURN_LAST_ERROR_IF_NULL_EXPECTED
#define RETURN_IF_NTSTATUS_FAILED RETURN_IF_NTSTATUS_FAILED_EXPECTED
